language: python
install: gem install fpm
before_script:
- curl -s http://arduino.googlecode.com/files/arduino-${ARDUINO_IDE_VERSION}-linux64.tgz
  | sudo tar xz -C /opt
- git clone -q https://github.com/BrianAdams/hwci-scripts ../hwci-scripts && ../hwci-scripts/bin/setup.sh
- sudo apt-get install cppcheck
script:
- "   env USER_LIB_PATH=$PWD/../ ARDUINO_DIR=/opt/arduino-${ARDUINO_IDE_VERSION} ../hwci-scripts/bin/arduino_make.sh
  -C OpenROV && echo pass:$e >> results || echo fail:$e >> results "
- cat results
- 'cut -d: -f1 results | sort | uniq -c'
- test `grep -c fail results` -eq 0
env:
  global:
  - ARDUINO_IDE_VERSION='1.0.5'
  - VERSION_NUMBER="`cat package.json | grep version | grep -o '[0-9]\.[0-9]\.[0-9]\+'`"
  - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  - secure: "P4i5RD2+chpGAPtkn1JYChOc+TVEHdHVVWA40uVAaHqRGm0I/kAvA2i4xXun0VAFFJJjQgC7BSdzQs9kP6IVu4x7VVXyOt3OYMql8ehsH6LU3Q476Rb+HIOzX30qYx+7F+cHUPFp/BTiyEJ+IOjU6sDTWLmSDpjUvVD2Tzg+PLI="
  - REAL_GIT_BRANCH="`git for-each-ref --format='%(objectname) %(refname:short)' refs/heads
    | grep $TRAVIS_COMMIT | awk '{print $2}'`"
after_success:
- echo version_number $VERSION_NUMBER
- echo real_get_branch $REAL_GIT_BRANCH
- rm -rf OpenROV/build-*
- 'fpm -f -m info@openrov.com -s dir -t deb -a armhf -n openrov-arduino-firmware -v
  $VERSION_NUMBER-$REAL_GIT_BRANCH.$BUILD_NUMBER.`git rev-parse --short HEAD` --description ''OpenROV Arduino Firmware'' .=/opt/openrov/arduino '
- mkdir build
- DEBFILE="`ls *.deb`""
- cp *.deb build/openrov-arduino-firmware_latest-${REAL_GIT_BRANCH}_armhf.deb
- mv *.deb build/
deploy:
  provider: s3
  access_key_id: AKIAIUN4NNHBKIOZE2JA
  secret_access_key:
    secure: Kj4ztuDp4T9dzkAERQSchEuT45Tiyh66R2uSiqPXWAjI8rR5GxGF8bPelPJeztKmzAO710x4eed7kx0wSKo/Cg9IX5YbpOoMqHbmGOeetpnWdcNCjujhMXnk0em/vQeEXSirwi1tUCFqlXK875kF+FpdzCd+kENDiYRs+rCCp0M=
  bucket: openrov-software-nightlies
  skip_cleanup: true
  region: us-west-2
  endpoint: bucket-name.s3-website-us-west-2.amazonaws.com
  local-dir: build
  upload-dir: arduino-firmware
  acl: !ruby/string:HighLine::String public_read
  on:
    repo: OpenROV/openrov-software-arduino
    all_branches: true
    condition: "($REAL_GIT_BRANCH = master )||($REAL_GIT_BRANCH = pre-release )||($REAL_GIT_BRANCH = stable)"
after_deploy:
- curl -g http://build.openrov.com:8080/job/OpenROV-generic-upload-deb-to-repo/buildWithParameters -d token=$JENKINS_TOKEN_NAME -d urlToDebPackage=http://openrov-software-nightlies.s3-website-us-west-2.amazonaws.com/openrov-software-arduino%2F$DEBFILE -d branch=$REAL_GIT_BRANCH

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/75083394acfa5b6df091
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
